### ISSUE TITLE
Error when aligning prenormalized tiffs

### ISSUE THREAD

**Issue by DoranPennington** [swelborn/tomopyui#35]
I've been running into an error where I'm not able to finish aligning my tiff files, it says TypeError: NoneType object is not iterable

It writes a folder in my data directory that contains normalized_projections.hdf5, import_metadata.json, and an alignment folder which only contains a 14 kB overall_alignment_metadata.json file. Here is the full error output

`TypeError                                 Traceback (most recent call last)
File ~\tomopyui\tomopyui\widgets\analysis.py:385, in AnalysisBase.set_options_and_run(self, change)
    381 change.icon = "fas fa-cog fa-spin fa-lg"
    382 change.description = (
    383     "Setting options and loading data into alignment algorithm."
    384 )
--> 385 self.run()
    386 change.button_style = "success"
    387 change.icon = "fa-check-square"

File ~\tomopyui\tomopyui\widgets\analysis.py:652, in Align.run(self)
    651 def run(self):
--> 652     self.analysis = TomoAlign(self)
    653     self.analysis_projections = Projections_Prenormalized()
    654     self.analysis_projections.data = self.analysis.projections_aligned

File ~\tomopyui\tomopyui\backend\align.py:49, in TomoAlign.__init__(self, Align)
     47 self.plot_output2 = Align.plot_output2
     48 self.make_wd()
---> 49 self.run()

File ~\tomopyui\tomopyui\backend\align.py:260, in TomoAlign.run(self)
    258 self.init_prj()
    259 tic = perf_counter()
--> 260 self.align()
    261 # make new dataset and pad/shift it
    262 self._shift_prjs_after_alignment()

File ~\tomopyui\tomopyui\backend\align.py:159, in TomoAlign.align(self)
    154 if (
    155     method in astra_cuda_recon_algorithm_underscores
    156     and os.environ["cuda_enabled"] == "True"
    157 ):
    158     self.current_align_is_cuda = True
--> 159     align_joint_cupy(self)
    160 else:
    161     self.current_align_is_cuda = False

File ~\tomopyui\tomopyui\tomocupy\prep\alignment.py:58, in align_joint(TomoAlign)
     56 subset_x = TomoAlign.subset_x
     57 subset_y = TomoAlign.subset_y
---> 58 subset_x = [int(x) + pad_ds[0] for x in subset_x]
     59 subset_y = [int(y) + pad_ds[1] for y in subset_y]
     60 # Initialize projection images plot

TypeError: 'NoneType' object is not iterable`

**Comment by swelborn** [comment]
Hey @DoranPennington is this solved with the latest updates?
