### ISSUE TITLE
Cannot load APS dataset from Tomobank

### ISSUE THREAD

**Issue by Z-Peter-Li** [swelborn/tomopyui#56]
Hi Sam! 
I've been trying to load multiple .h5 files downloaded from Tomobank using the 'APS' data type but encountered some problems. According to Tomobank, the dataset I am using (tomo_00086) is collected at APS32ID. When I selected the .h5 file, the import button on the import page is not activated. Do you have any idea why this might happen? Please see the screenshot below. Many thanks!
![Screenshot 2024-08-12 at 22 43 06](https://github.com/user-attachments/assets/c661fc75-e267-40b0-a8f8-10727d40ed0c)

**Comment by swelborn** [comment]
Hey Zhiyuan, thanks for reaching out. 

I will also post your email here for posterity:

> I downloaded tomo_00086.h5 and tried to import it into the GUI but the upload icon remains dark after I selected the file and the warning No file or directory with that name popped up as shown:
> ![Screenshot 2024-08-14 at 10 02 02](https://github.com/user-attachments/assets/a61eda56-75fc-4873-ad9f-e997510153f4)
> 
> I tried to select the fake_als_data.h5 I found in the example folder and it worked just fine in both APS and ALS-832 modes. The dimensions of the example .h5 file and the tomobank file are as shown:
> 
> Example file
> ![Screenshot 2024-08-14 at 10 04 10](https://github.com/user-attachments/assets/4041ca9b-404c-4963-b032-351b43bbb6b7)
> Tomobank file
> ![unnamed (1)](https://github.com/user-attachments/assets/fe499625-f9bd-48c2-9715-c79de2dad74a)

The "raw data" import tab is a little trickier than pulling in pre-normalized data. You have to create your own data importer to do this. Here is some prior art for this: https://github.com/swelborn/tomopyui/pull/41

I made one for APS, but it is not currently in the main branch of this repository, it is under this branch: https://github.com/swelborn/tomopyui/tree/APS_tomobank

You can run `git checkout APS_tomobank` if you downloaded the github repository.

I will eventually merge this into the main branch so this won't be necessary. However, I do not have time this week to do it.

If you want, you can normalize your data to create a stack of normalized tiffs (see here: https://tomopy.readthedocs.io/en/latest/ipynb/tomopy.html), and import them into the second "Import Prenormalized Data" box on the `Import` tab.

**Comment by Z-Peter-Li** [comment]
Dear Sam,

Thank you very much for your prompt reply and the numerous alternatives you provided!
The latter method of importing a pre-normalized tiff folder seems to work well. I'll stick with that for now.

Best regards,

Peter

**Comment by Z-Peter-Li** [comment]
Dear Sam,

Thank you very much for your prompt reply and the numerous alternatives you
provided!

The latter method of importing a pre-normalized tiff folder seems to work
well. I'll stick with that for now.
Best regards,

Peter (Zhiyuan) Li
--------------------------------------------------
Zhiyuan Li (he/him)
Doctorate Student
Department of Mechanical Engineering
*Northwestern University*
2145 Sheridan Road, Tech B139, Evanston, IL, 60208
Email: ***@***.***

Phone: +1 (872) 239-9396

**Comment by swelborn** [comment]
ok. just create another issue here if you come across a new one.
